### ISSUE TITLE
Naming / overlap / difference with existing qpip

### ISSUE THREAD

**Issue by m-kuhn** [cnheider/eqip#1]
There is another plugin [qpip](https://github.com/opengisch/qpip) that already exists for some time with similar goals as this one as far as I can tell.
Is there any overlap in functionality or differences that make it unsuitable for your use case?

I think for functionality like this, the QGIS ecosystem will benefit from one "best practice" approach to handle this. :wave:

**Comment by cnheider** [comment]
Hello, I decide to rebrand to the plugin to "Eqip" to avoid collisions but never got around delisted it, I will get this done shortly.

@kannes I will release a major update soon and along with CI pipeline for future releases 🥁
